
palindrome_linked_list: libgtest.a palindrome_linked_list.o
	g++ libgtest.a palindrome_linked_list.o -o palindrome_linked_list

palindrome_linked_list.o: palindrome_linked_list.cpp
	g++ -I ../googletest/googletest/include/ -c palindrome_linked_list.cpp -o palindrome_linked_list.o
